
services:
  ualflix_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ualflix
    ports:
      - "5432:5432"
    networks:
      - ualflix_network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  catalog_service:
    build: ./catalog_service
    depends_on:
      - ualflix_db
    ports:
      - "8000:8000"
    networks:
      - ualflix_network
    volumes:
      - video_storage:/videos

  streaming_service:
    build: ./streaming_service
    ports:
      - "8001:8001"
    networks:
      - ualflix_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - ualflix_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - video_storage:/videos
    depends_on:
      - frontend
      - catalog_service
      - streaming_service
    networks:
      - ualflix_network

volumes:
  db_data:
  video_storage:

networks:
  ualflix_network:
    driver: bridge